### PR TITLE
fix lake.ros

### PR DESCRIPTION
**Pull request by snmsts**

### CODE REVIEW

**Comment by smashedtoatoms** [comment]
Any chance we can get this merged?

**Comment by takagi** [comment]
Super sorry, I completely dropped this...
Thanks, @snmsts! Also @smashedtoatoms for letting me know it!

**Comment by smashedtoatoms** [comment]
No problem at all!  I went through my projects when my daughter turned 3 and realized I had completely forgotten to pull PRs in almost half of them.  Thanks for jumping on that one.

**Comment by snmsts** [comment]
@takagi Thank you!

**Comment by takagi** [comment]
@smashedtoatoms  Reising a child is quite tough work. I will have my third child this summer, maybe another boy. Three children in four years, an extremely high reproduction rate!

@snmsts Long time no see, friend! How are you?

**Pull request merged**
