### PR TITLE
Build lake with asdf and homebrew on OSX

### PR DESCRIPTION
**Pull request by svetlyak40wt**
This pull makes it possible to install `lake` as a binary by doing:

```
brew tap takagi/lake https://github.com/takagi/lake
brew install lake
```

This formula does not build a `lake-tools`. Maybe it is better to integrate `init` functionality right into a `lake` – and ask if the user wants to create a `Lakefile` if it is absent in the current directory?

After merging, you need to:

* bump version number;
* add and push git tag with version number in format v0.1.4
* regenerate a homebrew formula with `lake update-formula` command. You'll need a fresh [Qlot](https://github.com/fukamachi/qlot) and [this version](https://github.com/svetlyak40wt/cl-brewer) of `cl-brewer` to do this.

P.S. – right now binary is installable by:

```
brew tap takagi/lake https://github.com/svetlyak40wt/lake
brew install lake
```

### CODE REVIEW

**Comment by svetlyak40wt** [comment]
Please, don't merge this pull request yet. I want to update readme and changelog.

**Comment by svetlyak40wt** [comment]
@takagi please, review this pull. It is ready now.

**Comment by svetlyak40wt** [comment]
@takagi please, review this pull request.

**Comment by takagi** [comment]
Sorry for my late reply. I'll review to merge it soon.

**Comment by svetlyak40wt** [comment]
@takagi hi :)

How about merging this pull?

**Comment by takagi** [comment]
Now I've merged it. Thanks!

**Pull request merged**
